# apiVersion: v1
# kind: Secret
# metadata:
#   name: db-credentials
#   namespace: {{ .Values.namespace }}
# type: Opaque
# stringData:
#   SPRING_DATASOURCE_USERNAME: {{ .Values.dbCredentials.username }}
#   SPRING_DATASOURCE_PASSWORD: {{ .Values.dbCredentials.password }}
#   SPRING_DATASOURCE_WRITER_URL: {{ .Values.dbCredentials.writerUrl }}


apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: {{ .Values.dbCredentials.username }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.dbCredentials.password }}
  SPRING_DATASOURCE_WRITER_URL: {{ .Values.dbCredentials.writerUrl }}
