apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: crewmeister-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - crewmeister
  selector:
    matchLabels:
      app: crewmeister
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
