apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: crewmeister-monitor
  namespace: {{ .Values.namespace }}
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - crewmeister
  selector:
    matchLabels:
      app: crewmeister
  endpoints:
    - port: {{ .Values.serviceMonitor.port }}
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}